import NavBar from "./components/navbar";
import "./globals.css";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Comfortaa } from "next/font/google";
import localFont from "next/font/local";
export const myFont = localFont({
  src: "./fonts/Axis_Extrabold.otf",
  display: "swap",
});
const comfortaa = Comfortaa({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${comfortaa.className}`}>
        <Providers>
          <div className="background"></div>
          <main className="m-auto w-[90vw]">
            <NavBar />
            {children}
          </main>
        </Providers>
      </body>
    </html>
  );
}
